### ISSUE TITLE
Epic tracking issue

### ISSUE THREAD

**Issue by sciwhiz12** [sciwhizlabs/testing#4]
Truly epic.

```[tasklist]
# High priority
- [x] Ensure booping can be done
- [x] Order sufficient amount of fox-box
- [ ] License bolb from official source
```

```[tasklist]
# Medium priority
- [x] Correct boopage outside certain parameters
- [ ] https://github.com/sciwhizlabs/testing/issues/5
- [ ] Integrate end user feedback
```

```[tasklist]
# Low priority
- [x] Investigate foxing issue during timeouts
- [x] Correct license header years
- [ ] Run test CI build
```
